crawler:
  apiKey:
  agent: Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0
  numOfThreads: 5
  crawlDelay: 200
  workFolder: target/crawl/root
  baseUrl: http://v1.syndication.nhschoices.nhs.uk/conditions/
  startUrl: http://v1.syndication.nhschoices.nhs.uk/conditions/atoz
  enabled: true

elasticsearch:
  dbPath: target/elasticsearch-data
  nodeName: nhs_cache
  indexName: conditions
  typeName: nhs_page
